name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  rust:
    name: Rust - fmt, clippy, tests, docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Format check
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Tests
        run: cargo test
      - name: Docs
        run: cargo doc --no-deps

  python-api:
    name: Python API tests (maturin develop + pytest)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python deps
        run: |
          python -m pip install -U pip
          python -m pip install -U maturin pytest numpy
      - name: Build and install extension (develop)
        run: |
          maturin develop -m pyproject.toml
      - name: Run Python API tests
        run: |
          pytest -q tests_py
